#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = Path("/private/tmp") / "lerobot_sim" / "so101_source_authority_matrix"
SCHEMA = "lerobot.sim.so101_source_authority_matrix.v1"
INVENTORY_SCRIPT = REPO_ROOT / "scripts" / "smoke_sim_so101_model_source_inventory.py"
EXPECTED_TARGET_FRAME = "gripper_frame_link"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run a hardware-free matrix over SO-101 model-source authority states. "
            "Synthetic fixture URDFs are generated under the output directory and are "
            "explicitly not reviewed physical SO-101 truth."
        )
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--python",
        type=Path,
        default=Path(sys.executable),
        help="Python executable used for child source-inventory subprocesses.",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Do not delete an existing output directory before running.",
    )
    return parser.parse_args()


def normalize_path(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def executable_arg(path: Path) -> str:
    raw = str(path)
    expanded = path.expanduser()
    if expanded.is_absolute():
        return str(expanded)
    if "/" in raw:
        return str((REPO_ROOT / expanded).absolute())
    return raw


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def csv_cell(value: Any) -> str:
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, sort_keys=True)
    if value is None:
        return ""
    return str(value)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = (
        "case_id",
        "ok",
        "inventory_status",
        "candidate_count",
        "authoritative_candidate_count",
        "selected_authoritative_candidate_path",
        "selected_authoritative_candidate_sha256",
        "source_authority_gate_status",
        "source_authority_review_status",
        "source_authority_review_ready",
        "review_evidence_valid_fields",
        "review_evidence_missing_required_groups",
        "source_intake_status",
        "source_intake_model_authority",
        "source_intake_action_ids",
        "review_packet_status",
        "review_packet_model_authority",
        "physical_so101_model_authority_ready",
        "development_fixture_evidence_not_physical_so101_truth",
        "expected_status",
        "summary_path",
        "errors",
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: csv_cell(row.get(field)) for field in fieldnames})


def synthetic_urdf(robot_name: str) -> str:
    return f"""<?xml version="1.0"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Synthetic SO-101 source-authority matrix fixture generated by smoke_sim_so101_source_authority_matrix.py. -->
<!-- onshape-to-robot provenance marker is fixture evidence only, not physical SO-101 authority. -->
<robot name="{robot_name}">
  <link name="base_link"/>
  <link name="shoulder_pan_link"/>
  <link name="shoulder_lift_link"/>
  <link name="elbow_flex_link"/>
  <link name="wrist_flex_link"/>
  <link name="{EXPECTED_TARGET_FRAME}"/>

  <joint name="shoulder_pan" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_pan_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.919862" upper="1.919862" effort="1" velocity="1"/>
  </joint>
  <joint name="shoulder_lift" type="revolute">
    <parent link="shoulder_pan_link"/>
    <child link="shoulder_lift_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.919862" upper="1.919862" effort="1" velocity="1"/>
  </joint>
  <joint name="elbow_flex" type="revolute">
    <parent link="shoulder_lift_link"/>
    <child link="elbow_flex_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.094395" upper="2.094395" effort="1" velocity="1"/>
  </joint>
  <joint name="wrist_flex" type="revolute">
    <parent link="elbow_flex_link"/>
    <child link="wrist_flex_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.094395" upper="2.094395" effort="1" velocity="1"/>
  </joint>
  <joint name="wrist_roll" type="revolute">
    <parent link="wrist_flex_link"/>
    <child link="{EXPECTED_TARGET_FRAME}"/>
    <axis xyz="1 0 0"/>
    <limit lower="-3.141593" upper="3.141593" effort="1" velocity="1"/>
  </joint>
</robot>
"""


def create_fixtures(output_dir: Path) -> dict[str, Path]:
    fixture_dir = output_dir / "fixtures"
    single_root = fixture_dir / "single_source_root"
    ambiguous_root = fixture_dir / "ambiguous_source_root"
    missing_root = fixture_dir / "missing_source_root"
    single_root.mkdir(parents=True, exist_ok=True)
    ambiguous_root.mkdir(parents=True, exist_ok=True)
    (single_root / "LICENSE").write_text("Synthetic fixture license for hardware-free smoke testing only.\n")
    (ambiguous_root / "LICENSE").write_text("Synthetic fixture license for hardware-free smoke testing only.\n")

    single_model = single_root / "so101_synthetic_source.urdf"
    ambiguous_a = ambiguous_root / "so101_synthetic_source_a.urdf"
    ambiguous_b = ambiguous_root / "so101_synthetic_source_b.urdf"
    single_model.write_text(synthetic_urdf("so101_synthetic_source"))
    ambiguous_a.write_text(synthetic_urdf("so101_synthetic_source_a"))
    ambiguous_b.write_text(synthetic_urdf("so101_synthetic_source_b"))

    return {
        "single_root": single_root,
        "single_model": single_model,
        "ambiguous_root": ambiguous_root,
        "ambiguous_model_a": ambiguous_a,
        "ambiguous_model_b": ambiguous_b,
        "missing_root": missing_root,
    }


def complete_review_args() -> list[str]:
    return [
        "--authority-license-basis",
        "synthetic fixture license for hardware-free source-authority matrix only",
        "--authority-review-scope",
        "model_identity",
        "--authority-review-scope",
        "provenance",
        "--authority-review-scope",
        "license",
        "--authority-reviewed-by",
        "smoke_sim_so101_source_authority_matrix",
        "--authority-reviewed-at",
        "2026-06-18",
        "--authority-review-id",
        "source-authority-matrix-fixture",
        "--authority-source-reference",
        "generated synthetic fixture under the smoke output directory",
    ]


def placeholder_review_args() -> list[str]:
    return [
        "--authority-license-basis",
        "synthetic fixture license for hardware-free source-authority matrix only",
        "--authority-review-scope",
        "model_identity",
        "--authority-review-scope",
        "provenance",
        "--authority-review-scope",
        "license",
        "--authority-reviewed-by",
        "TODO",
        "--authority-reviewed-at",
        "TBD",
    ]


def thin_review_args() -> list[str]:
    return [
        "--authority-license-basis",
        "synthetic fixture license for hardware-free source-authority matrix only",
        "--authority-review-scope",
        "model_identity",
        "--authority-review-scope",
        "provenance",
        "--authority-review-scope",
        "license",
        "--authority-reviewed-by",
        "smoke_sim_so101_source_authority_matrix",
    ]


def case_specs(fixtures: dict[str, Path]) -> list[dict[str, Any]]:
    single_model_sha256 = sha256_file(fixtures["single_model"])
    return [
        {
            "case_id": "missing_source_root",
            "args": ["--root", str(fixtures["missing_root"])],
            "expect": {
                "status": "missing_authoritative_model",
                "candidate_count": 0,
                "authoritative_candidate_count": 0,
                "source_authority_gate_status": "source_authority_blocked_missing_authoritative_model",
                "source_authority_review_status": "not_applicable_no_authoritative_candidate",
                "source_authority_review_ready": False,
                "source_intake_status": "source_root_required",
                "review_packet_status": "review_packet_waiting_for_model_source_root",
                "blockers_contain": [
                    "scan_or_supply_so101_model_source_root",
                    "review_and_declare_authoritative_so101_model_source",
                ],
                "actions_contain": [
                    "scan_or_supply_so101_model_source_root",
                    "review_and_declare_authoritative_so101_model_source",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
            },
        },
        {
            "case_id": "candidate_unverified",
            "args": ["--root", str(fixtures["single_root"])],
            "expect": {
                "status": "missing_authoritative_model",
                "candidate_count": 1,
                "authoritative_candidate_count": 0,
                "source_authority_gate_status": "source_authority_blocked_missing_authoritative_model",
                "source_authority_review_status": "not_applicable_no_authoritative_candidate",
                "source_authority_review_ready": False,
                "source_intake_status": "source_authority_review_required",
                "review_packet_status": "review_packet_source_candidates_need_authority_review",
                "blockers_contain": ["review_and_declare_authoritative_so101_model_source"],
                "actions_contain": [
                    "review_and_declare_authoritative_so101_model_source",
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
                "actions_absent": ["scan_or_supply_so101_model_source_root"],
            },
        },
        {
            "case_id": "authoritative_missing_review_metadata",
            "args": [
                "--root",
                str(fixtures["single_root"]),
                "--authoritative-path",
                str(fixtures["single_model"]),
            ],
            "expect": {
                "status": "authoritative_model_found",
                "candidate_count": 1,
                "authoritative_candidate_count": 1,
                "source_authority_gate_status": "source_authority_blocked_review_metadata",
                "source_authority_review_status": "review_metadata_missing",
                "source_authority_review_ready": False,
                "source_intake_status": "source_review_metadata_required",
                "review_packet_status": "review_packet_source_authority_review_metadata_needed",
                "blockers_contain": ["record_source_authority_review_metadata"],
                "actions_contain": [
                    "record_source_authority_review_metadata",
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
            },
        },
        {
            "case_id": "authoritative_placeholder_review_metadata",
            "args": [
                "--root",
                str(fixtures["single_root"]),
                "--authoritative-path",
                str(fixtures["single_model"]),
                *placeholder_review_args(),
            ],
            "expect": {
                "status": "authoritative_model_found",
                "candidate_count": 1,
                "authoritative_candidate_count": 1,
                "source_authority_gate_status": "source_authority_blocked_review_metadata",
                "source_authority_review_status": "review_metadata_missing",
                "source_authority_review_ready": False,
                "source_intake_status": "source_review_metadata_required",
                "review_packet_status": "review_packet_source_authority_review_metadata_needed",
                "blockers_contain": ["record_source_authority_review_metadata"],
                "actions_contain": [
                    "record_source_authority_review_metadata",
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
                "placeholder_review_fields_contain": [
                    "authority_reviewed_at",
                    "authority_reviewed_by",
                ],
            },
        },
        {
            "case_id": "authoritative_thin_review_metadata",
            "args": [
                "--root",
                str(fixtures["single_root"]),
                "--authoritative-path",
                str(fixtures["single_model"]),
                *thin_review_args(),
            ],
            "expect": {
                "status": "authoritative_model_found",
                "candidate_count": 1,
                "authoritative_candidate_count": 1,
                "source_authority_gate_status": "source_authority_blocked_review_metadata",
                "source_authority_review_status": "review_metadata_missing",
                "source_authority_review_ready": False,
                "source_intake_status": "source_review_metadata_required",
                "review_packet_status": "review_packet_source_authority_review_metadata_needed",
                "blockers_contain": ["record_source_authority_review_metadata"],
                "actions_contain": [
                    "record_source_authority_review_metadata",
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
                "review_evidence_valid_fields_contain": ["authority_reviewed_by"],
                "review_evidence_satisfied_required_groups_contain": ["review_actor"],
                "review_evidence_missing_required_groups_contain": ["review_trace"],
                "missing_required_fields_contain": ["authority_review_evidence:review_trace"],
            },
        },
        {
            "case_id": "authoritative_complete_source_review",
            "args": [
                "--root",
                str(fixtures["single_root"]),
                "--authoritative-path",
                str(fixtures["single_model"]),
                *complete_review_args(),
            ],
            "expect": {
                "status": "authoritative_model_found",
                "candidate_count": 1,
                "authoritative_candidate_count": 1,
                "source_authority_gate_status": "source_authority_ready",
                "source_authority_review_status": "review_metadata_supplied",
                "source_authority_review_ready": True,
                "source_intake_status": "source_authority_ready_waiting_for_bundle_manifest",
                "review_packet_status": "review_packet_source_authority_ready",
                "selected_authoritative_candidate_path": str(normalize_path(fixtures["single_model"])),
                "selected_authoritative_candidate_sha256": single_model_sha256,
                "blockers_exact": [],
                "actions_contain": [
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
                "missing_review_scope_ids": [],
            },
        },
        {
            "case_id": "authoritative_single_root_complete_source_review",
            "args": [
                "--root",
                str(fixtures["single_root"]),
                "--authoritative-root",
                str(fixtures["single_root"]),
                *complete_review_args(),
            ],
            "expect": {
                "status": "authoritative_model_found",
                "candidate_count": 1,
                "authoritative_candidate_count": 1,
                "source_authority_gate_status": "source_authority_ready",
                "source_authority_review_status": "review_metadata_supplied",
                "source_authority_review_ready": True,
                "source_intake_status": "source_authority_ready_waiting_for_bundle_manifest",
                "review_packet_status": "review_packet_source_authority_ready",
                "selected_authoritative_candidate_path": str(normalize_path(fixtures["single_model"])),
                "selected_authoritative_candidate_sha256": single_model_sha256,
                "blockers_exact": [],
                "actions_contain": [
                    "run_so101_model_bundle_probe",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
                "missing_review_scope_ids": [],
            },
        },
        {
            "case_id": "authoritative_root_ambiguous",
            "args": [
                "--root",
                str(fixtures["ambiguous_root"]),
                "--authoritative-root",
                str(fixtures["ambiguous_root"]),
                *complete_review_args(),
            ],
            "expect": {
                "status": "ambiguous_authoritative_model",
                "candidate_count": 2,
                "authoritative_candidate_count": 2,
                "source_authority_gate_status": "source_authority_blocked_ambiguous_authoritative_model",
                "source_authority_review_status": "review_metadata_supplied",
                "source_authority_review_ready": True,
                "source_intake_status": "single_source_selection_required",
                "review_packet_status": "review_packet_multiple_authoritative_candidates_need_selection",
                "blockers_contain": ["select_single_authoritative_so101_model_source"],
                "actions_contain": [
                    "select_single_authoritative_so101_model_source",
                    "supply_reviewed_so101_model_bundle_manifest",
                ],
            },
        },
    ]


def run_case(
    *,
    case_id: str,
    case_args: list[str],
    python_path: Path,
    output_dir: Path,
) -> tuple[dict[str, Any], dict[str, Any]]:
    case_dir = output_dir / case_id
    summary_path = case_dir / "so101_model_source_inventory_summary.json"
    python_executable = executable_arg(python_path)
    command = [
        python_executable,
        str(INVENTORY_SCRIPT),
        "--output-dir",
        str(case_dir),
        "--sample-bytes",
        "256000",
        *case_args,
    ]
    result = subprocess.run(command, cwd=REPO_ROOT, text=True, capture_output=True, check=False)
    stdout_path = case_dir / f"{case_id}_stdout.txt"
    stderr_path = case_dir / f"{case_id}_stderr.txt"
    stdout_path.parent.mkdir(parents=True, exist_ok=True)
    stdout_path.write_text(result.stdout)
    stderr_path.write_text(result.stderr)

    try:
        inventory = json.loads(summary_path.read_text())
    except Exception as exc:
        inventory = {
            "ok": False,
            "status": "summary_unavailable",
            "summary_error": f"{type(exc).__name__}: {exc}",
        }

    record = {
        "case_id": case_id,
        "command": command,
        "return_code": result.returncode,
        "stdout_path": str(stdout_path),
        "stderr_path": str(stderr_path),
        "summary_path": str(summary_path),
    }
    return record, inventory


def add_error(errors: list[str], label: str, actual: Any, expected: Any) -> None:
    if actual != expected:
        errors.append(f"{label}: expected {expected!r}, got {actual!r}")


def expect_contains(errors: list[str], label: str, values: Any, expected_values: list[str]) -> None:
    values = values if isinstance(values, list) else []
    for expected in expected_values:
        if expected not in values:
            errors.append(f"{label}: expected {expected!r} in {values!r}")


def expect_absent(errors: list[str], label: str, values: Any, absent_values: list[str]) -> None:
    values = values if isinstance(values, list) else []
    for absent in absent_values:
        if absent in values:
            errors.append(f"{label}: expected {absent!r} absent from {values!r}")


def summarize_case(record: dict[str, Any], inventory: dict[str, Any], expect: dict[str, Any]) -> dict[str, Any]:
    errors: list[str] = []
    case_id = str(record["case_id"])
    source_review = inventory.get("source_authority_review")
    source_review = source_review if isinstance(source_review, dict) else {}
    source_intake = inventory.get("source_intake_checklist")
    source_intake = source_intake if isinstance(source_intake, dict) else {}

    add_error(errors, f"{case_id}.return_code", record.get("return_code"), 0)
    add_error(errors, f"{case_id}.ok", inventory.get("ok"), True)
    for key in (
        "status",
        "candidate_count",
        "authoritative_candidate_count",
        "source_authority_gate_status",
        "source_authority_review_status",
        "source_authority_review_ready",
        "source_intake_status",
        "review_packet_status",
    ):
        if key in expect:
            add_error(errors, f"{case_id}.{key}", inventory.get(key), expect[key])

    add_error(
        errors,
        f"{case_id}.review_packet_model_authority",
        inventory.get("review_packet_model_authority"),
        "review_packet_not_authority",
    )
    add_error(
        errors,
        f"{case_id}.review_packet_observed_evidence_is_authority",
        inventory.get("review_packet_observed_evidence_is_authority"),
        False,
    )
    add_error(
        errors,
        f"{case_id}.review_packet_physical_so101_model_authority_ready",
        inventory.get("review_packet_physical_so101_model_authority_ready"),
        False,
    )
    add_error(
        errors,
        f"{case_id}.source_intake_model_authority",
        inventory.get("source_intake_model_authority"),
        "source_intake_not_authority",
    )
    add_error(
        errors,
        f"{case_id}.source_intake_observed_evidence_is_authority",
        inventory.get("source_intake_observed_evidence_is_authority"),
        False,
    )
    add_error(
        errors,
        f"{case_id}.source_intake_physical_so101_model_authority_ready",
        inventory.get("source_intake_physical_so101_model_authority_ready"),
        False,
    )
    add_error(
        errors,
        f"{case_id}.source_intake_development_fixture_evidence_not_physical_so101_truth",
        inventory.get("source_intake_development_fixture_evidence_not_physical_so101_truth"),
        True,
    )
    add_error(
        errors,
        f"{case_id}.source_intake_checklist_model_authority",
        source_intake.get("model_authority"),
        "source_intake_not_authority",
    )
    add_error(
        errors,
        f"{case_id}.source_intake_checklist_physical_ready",
        source_intake.get("physical_so101_model_authority_ready"),
        False,
    )
    add_error(
        errors,
        f"{case_id}.source_intake_action_ids_match_next_required",
        inventory.get("source_intake_action_ids"),
        inventory.get("next_required_action_ids"),
    )
    add_error(
        errors,
        f"{case_id}.review_packet_action_ids_match_next_required",
        inventory.get("review_packet_action_ids"),
        inventory.get("next_required_action_ids"),
    )
    add_error(
        errors,
        f"{case_id}.source_intake_action_count",
        inventory.get("source_intake_action_count"),
        len(inventory.get("source_intake_action_ids") or []),
    )
    if not all(isinstance(action.get("command"), list) for action in source_intake.get("actions") or []):
        errors.append(f"{case_id}.source_intake_commands: expected all commands to be lists")

    expect_contains(
        errors,
        f"{case_id}.source_authority_blockers",
        inventory.get("source_authority_blockers"),
        expect.get("blockers_contain", []),
    )
    if "blockers_exact" in expect:
        add_error(
            errors,
            f"{case_id}.source_authority_blockers_exact",
            inventory.get("source_authority_blockers"),
            expect["blockers_exact"],
        )
    expect_contains(
        errors,
        f"{case_id}.next_required_action_ids",
        inventory.get("next_required_action_ids"),
        expect.get("actions_contain", []),
    )
    expect_absent(
        errors,
        f"{case_id}.next_required_action_ids",
        inventory.get("next_required_action_ids"),
        expect.get("actions_absent", []),
    )
    expect_contains(
        errors,
        f"{case_id}.review_evidence_placeholder_fields",
        source_review.get("review_evidence_placeholder_fields"),
        expect.get("placeholder_review_fields_contain", []),
    )
    expect_contains(
        errors,
        f"{case_id}.review_evidence_valid_fields",
        source_review.get("review_evidence_valid_fields"),
        expect.get("review_evidence_valid_fields_contain", []),
    )
    expect_contains(
        errors,
        f"{case_id}.review_evidence_satisfied_required_groups",
        source_review.get("review_evidence_satisfied_required_groups"),
        expect.get("review_evidence_satisfied_required_groups_contain", []),
    )
    expect_contains(
        errors,
        f"{case_id}.review_evidence_missing_required_groups",
        source_review.get("review_evidence_missing_required_groups"),
        expect.get("review_evidence_missing_required_groups_contain", []),
    )
    expect_contains(
        errors,
        f"{case_id}.source_authority_missing_required_fields",
        source_review.get("missing_required_fields"),
        expect.get("missing_required_fields_contain", []),
    )
    if "missing_review_scope_ids" in expect:
        add_error(
            errors,
            f"{case_id}.source_authority_missing_review_scope_ids",
            inventory.get("source_authority_missing_review_scope_ids"),
            expect["missing_review_scope_ids"],
        )
    if "selected_authoritative_candidate_path" in expect:
        add_error(
            errors,
            f"{case_id}.selected_authoritative_candidate_path",
            inventory.get("selected_authoritative_candidate_path"),
            expect["selected_authoritative_candidate_path"],
        )
    if "selected_authoritative_candidate_sha256" in expect:
        add_error(
            errors,
            f"{case_id}.selected_authoritative_candidate_sha256",
            inventory.get("selected_authoritative_candidate_sha256"),
            expect["selected_authoritative_candidate_sha256"],
        )

    return {
        "case_id": case_id,
        "ok": not errors,
        "status": "ok" if not errors else "failed",
        "errors": errors,
        "expected": expect,
        "record": record,
        "summary_path": record["summary_path"],
        "observations": {
            "inventory_status": inventory.get("status"),
            "candidate_count": inventory.get("candidate_count"),
            "likely_candidate_count": inventory.get("likely_candidate_count"),
            "direct_contract_candidate_count": inventory.get("direct_contract_candidate_count"),
            "authoritative_candidate_count": inventory.get("authoritative_candidate_count"),
            "authoritative_source_selection_status": inventory.get(
                "authoritative_source_selection_status"
            ),
            "selected_authoritative_candidate_path": inventory.get(
                "selected_authoritative_candidate_path"
            ),
            "selected_authoritative_candidate_sha256": inventory.get(
                "selected_authoritative_candidate_sha256"
            ),
            "source_authority_gate_status": inventory.get("source_authority_gate_status"),
            "source_authority_blockers": inventory.get("source_authority_blockers"),
            "source_authority_review_status": inventory.get("source_authority_review_status"),
            "source_authority_review_ready": inventory.get("source_authority_review_ready"),
            "source_authority_missing_review_scope_ids": inventory.get(
                "source_authority_missing_review_scope_ids"
            ),
            "source_authority_review_evidence_valid_fields": source_review.get(
                "review_evidence_valid_fields"
            ),
            "source_authority_review_evidence_missing_required_groups": source_review.get(
                "review_evidence_missing_required_groups"
            ),
            "source_authority_review": source_review,
            "source_intake_status": inventory.get("source_intake_status"),
            "source_intake_model_authority": inventory.get("source_intake_model_authority"),
            "source_intake_action_ids": inventory.get("source_intake_action_ids"),
            "source_intake_physical_so101_model_authority_ready": inventory.get(
                "source_intake_physical_so101_model_authority_ready"
            ),
            "review_packet_status": inventory.get("review_packet_status"),
            "review_packet_model_authority": inventory.get("review_packet_model_authority"),
            "review_packet_physical_so101_model_authority_ready": inventory.get(
                "review_packet_physical_so101_model_authority_ready"
            ),
            "next_required_action_ids": inventory.get("next_required_action_ids"),
            "artifacts": inventory.get("artifacts"),
        },
    }


def flatten_case(case: dict[str, Any]) -> dict[str, Any]:
    observations = case["observations"]
    return {
        "case_id": case["case_id"],
        "ok": case["ok"],
        "inventory_status": observations.get("inventory_status"),
        "candidate_count": observations.get("candidate_count"),
        "authoritative_candidate_count": observations.get("authoritative_candidate_count"),
        "selected_authoritative_candidate_path": observations.get(
            "selected_authoritative_candidate_path"
        ),
        "source_authority_gate_status": observations.get("source_authority_gate_status"),
        "source_authority_review_status": observations.get("source_authority_review_status"),
        "source_authority_review_ready": observations.get("source_authority_review_ready"),
        "review_evidence_valid_fields": observations.get(
            "source_authority_review_evidence_valid_fields"
        ),
        "review_evidence_missing_required_groups": observations.get(
            "source_authority_review_evidence_missing_required_groups"
        ),
        "source_intake_status": observations.get("source_intake_status"),
        "source_intake_model_authority": observations.get("source_intake_model_authority"),
        "source_intake_action_ids": observations.get("source_intake_action_ids"),
        "review_packet_status": observations.get("review_packet_status"),
        "review_packet_model_authority": observations.get("review_packet_model_authority"),
        "physical_so101_model_authority_ready": observations.get(
            "source_intake_physical_so101_model_authority_ready"
        ),
        "development_fixture_evidence_not_physical_so101_truth": True,
        "expected_status": case["expected"].get("source_authority_gate_status"),
        "summary_path": case["summary_path"],
        "errors": case["errors"],
    }


def write_readme(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# SO-101 Source Authority Matrix",
        "",
        f"- `status`: `{summary['status']}`",
        f"- `case_count`: `{summary['case_count']}`",
        f"- `failed_cases`: `{', '.join(summary['failed_case_ids']) if summary['failed_case_ids'] else 'none'}`",
        f"- `summary_json`: `{summary['artifacts']['summary_json']}`",
        f"- `cases_csv`: `{summary['artifacts']['cases_csv']}`",
        "",
        "Synthetic fixture caveat: these generated URDFs are automation fixtures only. They are not reviewed physical SO-101 model authority.",
        "",
        "## Cases",
        "",
        "| Case | Status | Candidates | Authoritative | Source Gate | Review Status | Intake | Actions | Summary |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for case in summary["cases"]:
        observations = case["observations"]
        lines.append(
            "| `{case_id}` | `{status}` | `{candidates}` | `{authoritative}` | `{gate}` | `{review}` | `{intake}` | `{actions}` | `{summary_path}` |".format(
                case_id=case["case_id"],
                status=case["status"],
                candidates=observations.get("candidate_count"),
                authoritative=observations.get("authoritative_candidate_count"),
                gate=observations.get("source_authority_gate_status"),
                review=observations.get("source_authority_review_status"),
                intake=observations.get("source_intake_status"),
                actions=", ".join(observations.get("next_required_action_ids") or []),
                summary_path=case["summary_path"],
            )
        )
    lines.extend(
        [
            "",
            "## Caveats",
            "",
            "- Source-authority-ready fixture cases still report source-intake and review-packet artifacts as not authority.",
            "- Physical SO-101 model authority remains false in every case.",
            "- A reviewed bundle manifest with mesh roots, joint limits, target frame, TCP offset, and base-to-board alignment is still required before model-backed work is trusted.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    args = parse_args()
    output_dir = normalize_path(args.output_dir)
    if output_dir.exists() and not args.keep_existing:
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    fixtures = create_fixtures(output_dir)
    cases: list[dict[str, Any]] = []
    for spec in case_specs(fixtures):
        record, inventory = run_case(
            case_id=spec["case_id"],
            case_args=spec["args"],
            python_path=args.python,
            output_dir=output_dir,
        )
        cases.append(summarize_case(record, inventory, spec["expect"]))

    ok = all(case["ok"] for case in cases)
    summary_path = output_dir / "so101_source_authority_matrix_summary.json"
    csv_path = output_dir / "so101_source_authority_matrix_cases.csv"
    readme_path = output_dir / "README.md"
    summary = {
        "schema": SCHEMA,
        "ok": ok,
        "status": "ok" if ok else "validation_failed",
        "repo_root": str(REPO_ROOT),
        "output_dir": str(output_dir),
        "hardware_skipped": True,
        "gui_skipped": True,
        "openai_skipped": True,
        "case_count": len(cases),
        "case_ids": [case["case_id"] for case in cases],
        "failed_case_ids": [case["case_id"] for case in cases if not case["ok"]],
        "fixtures": {key: str(normalize_path(value)) for key, value in fixtures.items()},
        "cases": cases,
        "artifacts": {
            "summary_json": str(summary_path),
            "cases_csv": str(csv_path),
            "readme_md": str(readme_path),
        },
        "limitations": [
            "Synthetic URDF fixtures live under the smoke output directory and are not physical SO-101 calibration truth.",
            "The source-authority-ready case proves the inventory state transition only; it does not supply a reviewed bundle manifest.",
            "This smoke does not open robot hardware, cameras, GUI flows, network resources, or LLM/OpenAI paths.",
        ],
    }
    write_json(summary_path, summary)
    write_csv(csv_path, [flatten_case(case) for case in cases])
    write_readme(readme_path, summary)

    print(
        json.dumps(
            {
                "ok": ok,
                "status": summary["status"],
                "summary_json": str(summary_path),
                "cases_csv": str(csv_path),
                "readme_md": str(readme_path),
                "case_ids": summary["case_ids"],
                "failed_cases": summary["failed_case_ids"],
            },
            sort_keys=True,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
